---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: welcome-to-forestry.md
  label: Welcome to Forestry
  read_only: true
- type: heading
  label: Content
- type: document
  path: content/about.md
  label: About
- type: directory
  path: content/post
  label: Posts
  create: all
  match: "*"
  templates:
  - post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: vuepress build -d .vuepress/dist
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
