---
label: Base
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: datetime
  name: lastmod
  label: Last Modified
